Elementary concurrency protection

diff --git a/scripts/dhcp/dhclient-exit-hooks.d/post-dhcp-settings b/scripts/dhcp/dhclient-exit-hooks.d/post-dhcp-settings
--- a/scripts/dhcp/dhclient-exit-hooks.d/post-dhcp-settings
+++ b/scripts/dhcp/dhclient-exit-hooks.d/post-dhcp-settings
@@ -1,11 +1,16 @@
 #!/bin/bash
 #
+. /usr/local/sbin/firewall_defs.sh
+
 PATH=/sbin:/usr/local/bin:$PATH
 ROUTE_INFO_PATH=/var/lib/routes
-TIME_TRESHOLD=10
+TIME_TRESHOLD=30
 ETH0_DY_NAME=gw.asuka.dy.fi
 ETH1_DY_NAME=shell.asuka.dy.fi
 ETH2_DY_NAME=asuka.dy.fi
+
+LOCK_WAIT_SECS=15
+
 
 
 # Only update if
@@ -24,7 +29,39 @@ fi
 
 case $reason in
     BOUND|RENEW|REBIND|REBOOT|TIMEOUT)
-	
+
+	logger "Interface $interface entering lock contest"
+	sync
+
+	# Force only one script to execute at a time
+
+	LOCK_TRY_TIME=0
+
+	while [ $LOCK_TRY_TIME -lt $LOCK_WAIT_SECS ];
+	do
+	    if mkdir $SCRIPTS_LOCKDIR;
+	    then
+		# Lock acquired
+		break;
+	    else
+		# Lock not acquired, wait and try again
+		sleep 1;
+		LOCK_TRY_TIME=$(( LOCK_TRY_TIME+1 ));
+	    fi
+	done
+
+	if [ $LOCK_TRY_TIME -ge $LOCK_WAIT_SECS ];
+	then
+	    logger "Interface $interface could not get a lock! Exiting.";
+	    sync;
+	    exit 1;
+	fi
+
+	logger "Interface $interface has lock"
+	sync
+
+
+
 	# Usual case: First ones are BOUND, rest RENEW
 	
 	if [ "$interface" = "eth0" ];
@@ -80,6 +117,14 @@ case $reason in
 	    fi
 	    /usr/local/sbin/update_dy_fi_address.sh $interface $ETH2_DY_NAME
 	fi
+
+	# Releasing the lock
+	logger "Interface $interface exiting"
+	sync
+	rmdir $SCRIPTS_LOCKDIR
 	;;
+
 esac
+
+
 
